name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Ejecutar pruebas unitarias
        run: ./gradlew test
