name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Firebase Tools
      run: npm install -g firebase-tools

    - name: Build and deploy to Firebase Hosting
      if: github.ref == 'refs/heads/main'
      run: |
        npm run build
        firebase deploy --token $FIREBASE_TOKEN --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
